### ISSUE TITLE
directory filtering causes page reload

### ISSUE THREAD

**Issue by sheilasaia** [rladies/rladies.github.io#167]
Passing along this issue from R-Lady member Lydia Gibson who reported it to me (Sheila) via Slack.

From Lydia: "I find that when I try to filter the directory to find my entry that the page reloads everytime. I use iOS and macOS. Idk if anyone else has had this issue."

Screenshot provided:
![rladies_directory_error](https://github.com/rladies/rladies.github.io/assets/12959101/8f6dce12-32e2-4dae-b2eb-4e0639f1c9f1)

And follow up from Lydia: "I tried on my Mac after messaging you. It might just be iOS because the issue is with my iPad and iPhone for sure."

**Comment by drmowinckels** [comment]
I need to understand a little better what steps were taken for this to happen, as I am not able to reproduce it.

I can find your entry @lgibson7 at:
https://rladies.org/directory/#lydia-gibson

**Comment by lgibson7** [comment]
Hello @drmowinckels. I am only having the issue on iOS devices (iPhone and/or iPad). I try to search by location but after I make my selection (San Jose, CA, USA) the webpage crashes.![image](https://github.com/rladies/rladies.github.io/assets/87203716/904d68a8-3d00-411e-951e-31277ba4c332)![image](https://github.com/rladies/rladies.github.io/assets/87203716/23ac27d9-9867-4cb9-9542-58a7ea93d1ca)

**Comment by drmowinckels** [comment]
Hey!

thanks for the detailed description. I currently cant reproduce, since no filtering is working at all. This has happened before, when we've recently added a new entry where some mysterious formatting breaks the filtering. 

We are onboarding a new website team to the Global team as we speak, but I hope I can use this exact point to help the new team familiarize themselves with the setup :) 

In the mean time, if you want to search for a known individual, the entire directory is on a single page, meaning you can use your browsers search function to search for your name. At least you can find it that way, and we'll try to sort this out asap.

**Comment by lgibson7** [comment]
No worries. Thank you!

**Comment by drmowinckels** [comment]
I thought that code would fix it. It fixed _one_ problem, but there is still another entry messing things up :(
